name: Docker Selenium CI

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build Project
    runs-on: ubuntu-latest
    env:
      MAVEN_OPTS: "-Dmaven.repo.local=${{ github.workspace }}/repository"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          # We must fetch at least the immediate parents so that if this is
          # a pull request then we can checkout the head.
          fetch-depth: 2

      # If this run was triggered by a pull request event, then checkout
      # the head of the pull request instead of the merge commit.
      - run: git checkout HEAD^2
        if: ${{ github.event_name == 'pull_request' }}

      - name: Get current date
        id: date
        run: echo "NOW=$(date +'%Y-%m-%dT%H_%M_%S')" >> $GITHUB_ENV
      - name: Echo date variable
        run: echo $NOW

      - name: Build the Docker image
        run: docker build . --file DockerfileBrowser --tag browserdockerci:$NOW --build-arg CHROME_VERSION=92.0.4515.107-1

      - name: Cache Maven repository
        uses: actions/cache@v2
        with:
          path: "${{ github.workspace }}/repository"
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
            ${{ runner.os }}-

      - name: Run the tests in the Docker image
        run: docker run -t -v $(pwd):/usr/tests/src -w /usr/tests/src browserdockerci:$NOW mvn clean test -Pdev_bdd -Dtestng.dtd.http=true
