name: Docker Selenium CI

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build Project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get current date
        id: date
        run: echo "NOW=$(date +'%Y-%m-%dT%H_%M_%S')" >> $GITHUB_ENV
      - name: Echo date variable
        run: echo $NOW

      - name: Build the Docker image
        run: docker build . --file DockerfileBrowser --tag browserdockerci:$NOW --build-arg CHROME_VERSION=120.0.6099.304-1

      - name: Run the tests in the Docker image
        run: docker run -t -v $(pwd):/usr/tests/src -w /usr/tests/src browserdockerci:$NOW mvn clean test -Pdev_bdd -Dtestng.dtd.http=true
